import Head from 'next/head'
import Image from "next/image"
import Link from 'next/link'

export default function explore() {
    return (
        <div className="text-white bg-secondary">
            <Head>
                <title>Explore | AeroTrack</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="grid w-full py-10 place-items-center text-center">
                <h1 className="pb-2 text-5xl font-semibold tracking-wide lg:text-6xl">
                    Select Aricraft
                </h1>
                <div className="inline-flex h-1 bg-primary rounded-full w-96"></div>
            </div>

            <div className="flex flex-wrap flex-col-2 justify-around w-full px-16 py-8">

                <Link href='/dragon2' passHref>
                    <div className="m-8">
                        <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                            <div className="pb-8 border-4  border-primary rounded-lg">
                                <Image width="350" height="250" src="/dragon2.jpeg" alt="" /></div>
                            <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold bg-homeImg font-sourceSerifPro">SpaceX Dragon 2</div>
                        </div>
                    </div>
                </Link>

                <Link href='/starship' passHref>
                    <div className="m-8">
                        <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                            <div className="pb-8 border-4  border-primary rounded-lg">
                                <Image width="350" height="220" src="/starship.jpeg" alt="" /></div>
                            <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold bg-homeImg font-sourceSerifPro">SpaceX Starship</div>
                        </div>
                    </div>
                </Link>

                <Link href='/boeing757' passHref>
                    <div className="m-8">
                        <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                            <div className="pb-8 border-4  border-primary rounded-lg">
                                <Image width="350" height="220" src="/boeing757.jpeg" alt="" /></div>
                            <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold bg-homeImg font-sourceSerifPro">Boeing 757</div>
                        </div>
                    </div>
                </Link>

                <Link href='/boeing787' passHref>
                    <div className="m-8">
                        <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                            <div className="pb-8 border-4  border-primary rounded-lg">
                                <Image width="350" height="220" src="/boeing787.jpg" alt="" /></div>
                            <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold bg-homeImg font-sourceSerifPro">Boeing 787</div>
                        </div>
                    </div>
                </Link>

                <Link href='/ec135' passHref>
                    <div className="m-8">
                        <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                            <div className="pb-8 border-4  border-primary rounded-lg">
                                <Image width="350" height="220" src="/EC135.jpeg" alt="" /></div>
                            <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold bg-homeImg font-sourceSerifPro">Eurocopter EC 135</div>
                        </div>
                    </div>
                </Link>

                <div className="m-8">
                    <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105 border-4 border-primary rounded-lg">
                        <div className="grid place-content-center text-3xl text-center items-center align-middle h-full font-semibold font-sourceSerifPro">More Aircrafts comming soon..</div>
                    </div>
                </div>

            </div>
        </div>
    )
}
