import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import { drone } from '../components/Drone/Drone'
import { motion } from "framer-motion"

export default function Home() {

  const fadeLeft = {
    hidden: {
      opacity: 0,
      x: -80,
    },
    visible: {
      opacity: 1,
      x: 0,
      transition: {
        delay: 2.2,
      }
    },
  }

  useEffect(() => {
    drone()
  }, [])

  return (
    <div className="">
      <Head>
        <title>AeroTrack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-6xl h-screen   text-white">
        <div className="p-4 space-y-10 md:space-y-0 md:grid md:grid-cols-2 font-poppins md:mx-36 md:pt-48">

          <motion.div variants={fadeLeft} initial="hidden" animate="visible" className="pr-4 md:flex md:flex-col md:justify-center">

            <h2 className="self-center mb-4 text-5xl font-bold tracking-wider md:text-4xl lg:text-7xl">AeroTrack</h2>

            <p className="self-center text-xl tracking-wide text-justify font-base">AeroTrack is an AR-based web platform where students come across and learn about various aircraft and spacecraft with the help of interactive 3D Models and AR.</p>

            <Link href="/explore" passHref>
              <span className="md:w-1/3">
                <button className="p-2 px-8 mt-4 text-base font-semibold tracking-wider text-white border rounded-full shadow-sm md:w-full bg-red-50 bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 hover:shadow-lg ">Explore</button></span>
            </Link>

          </motion.div>

          <div className="">
            {/* <img src={} alt="img" className="" /> */}
          </div>

        </div>
      </main>

    </div>
  )
}
